from __future__ import annotations

NHL_STATS_BASE = "https://api.nhle.com/stats/rest/en"
GAME_TYPE_REGULAR_SEASON = 2
NORMALIZATION_FACTOR = 84 / 82

SKATER_GOAL_POINTS = 1
SKATER_ASSIST_POINTS = 1

GOALIE_GOAL_POINTS = 1
GOALIE_ASSIST_POINTS = 1
GOALIE_OT_LOSS_POINTS = 1
GOALIE_WIN_POINTS = 2
GOALIE_SHUTOUT_BONUS = 3

TEAM_OT_LOSS_POINTS = 1
TEAM_WIN_POINTS = 2

CATEGORIES = ("F", "D", "G", "T")
